export const UrlApi = {
  ApiUrl: 'http://192.168.1.174:9595/ApiPrueba/API/',
  usuario: 'USUARIO',
  persona: 'persona',
  login: 'login',
  revisarCodigoActivacion: 'usuario/activacion',
  loginFacebook: 'Singin',
  articulos: 'articulo',
  buscarUsuario: 'usuario/cambiar',
  passwordReset: 'usuario/cambiar_contraseña',
  traerProductosCarrito: 'ArticuloP/listado',
  buscarProductos: 'ArticuloP/producto/',
  codigoRecuperacion: 'usuario/comprobar',
  productos: '',
  carrito: '',
};
