export const UrlApi = {
  ApiUrl: 'http://192.168.1.174:9595/',
  usuario: 'ApiPrueba/API/USUARIO',
  persona: 'ApiPrueba/API/persona',
  login: 'ApiPrueba/API/login',
  revisarCodigoActivacion: 'ApiPrueba/API/usuario/activacion',
  loginFacebook: 'ApiPrueba/auth/Singin',
  articulos: 'ApiPrueba/API/articulo',
  buscarUsuario: 'ApiPrueba/API/usuario/cambiar',
  passwordReset: 'ApiPrueba/API/usuario/cambiar_contraseña',
  traerProductosCarrito: 'ApiPrueba/API/Articulo/listado',
  buscarProductos: 'ApiPrueba/API/Articulo/producto/',
  codigoRecuperacion: 'ApiPrueba/API/usuario/comprobar',
  productos: '',
  carrito: '',
};
